
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FaInstagram, FaFacebook, FaLinkedin, FaGithub } from "react-icons/fa";
import Navbar from "@/components/Navbar";
import { MobileNav } from "@/components/MobileNav";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MobileNav/>
      <Navbar />

        {children}
         <footer className="bg-black  text-[#D6C1A3] py-6">
      <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between px-6 gap-4">

        {/* Name */}
        <p className="text-sm">
          © 2026 Sanjay S
        </p>

        {/* Social Icons */}
       <div className="flex gap-5 text-lg">
  <a
    href="https://www.instagram.com/freak_of_master/"
    target="_blank"
    rel="noopener noreferrer"
    className="hover:text-white transition"
  >
    <FaInstagram className="cursor-pointer" />
  </a>

  <a
    href="https://www.facebook.com/sanjays2005"
    target="_blank"
    rel="noopener noreferrer"
    className="hover:text-white transition"
  >
    <FaFacebook className="cursor-pointer" />
  </a>

  <a
    href="https://www.linkedin.com/in/sanjay2005/"
    target="_blank"
    rel="noopener noreferrer"
    className="hover:text-white transition"
  >
    <FaLinkedin className="cursor-pointer" />
  </a>

  <a
    href="https://github.com/ssanjay2005"
    target="_blank"
    rel="noopener noreferrer"
    className="hover:text-white transition"
  >
    <FaGithub className="cursor-pointer" />
  </a>
</div>

      </div>
    </footer>
      </body>
    </html>
  );
}
